---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# nhkcovid

<!-- badges: start -->
<!-- badges: end -->

The goal of nhkcovid is to ...

## Installation

You can install the development version of nhkcovid from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("MTRBEKTCBT/nhkcovid")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(nhkcovid)

nhkcovid_origin <-
read_data(
  .dir = here::here("inst/extdata"),
  .ptn = "nhk_news",
  .f = readr::read_csv
)
```

```{r}
nhkcovid
```

```{r}
gdp2018_full |>
  ggplot(aes(tokyo_power_cv, value)) +
  geom_smooth(method = "lm") +
  geom_point() +
  labs(
    x = "東京倍率",
    y = "県民経済計算"
  ) +
  scale_y_continuous(labels = scales::comma)+
  theme_bw() +
    facet_wrap(~gdp, scales = "free_y")
```